config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#index'

  # Login 
  get     '/login',  to: 'sessions#new'
  post    '/login',  to: 'sessions#create'
  delete  '/logout', to: 'sessions#destroy'
  
  # Signup
  get     '/signup', to: 'users#new'
  post    '/signup', to: 'users#create'
  
  # OmniAuth
  get     '/auth/:provider/callback', to: 'sessions#create_omniauth'
  
  resources :users
  resources :activations,     only: [:new, :create, :edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :tasks,           only: [:create, :destroy, :edit, :update]
  resources :tasks,           only: [:change, :delete_all] do
    member do
      get :change
      delete :delete_all
    end
  end

  get     '/cookies', to: 'static_pages#cookies_eu'
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  
  def index
    if logged_in?
      @user  = current_user
      @todo_tasks = @user.tasks.todo
      @todo_count = @user.tasks.todo.count
      @done_tasks = @user.tasks.done
      @done_count = @user.tasks.done.count
      @task  = @user.tasks.build
    else
      @user = User.new
    end
  end

  def cookies_eu
  end
end

app/views/static_pages/cookies_eu.html.haml
.cookies-eu-container
  .text-center
    %a{href: root_path} ToDo

  %h2 COOKIES
    
  %p Cookies are small text files which are downloaded to your computer, tablet or mobile phone when you visit a website or application. The website or application may retrieve these cookies from your web browser (eg Internet Explorer, Mozilla Firefox or Google Chrome) each time you visit, so they can recognise you, remember your preferences and provide you with a more secure online experience.

  %p Generally, cookies are very useful and are a common method used by almost every website you visit because they help to make your online experience as smooth as possible. For security reasons, many websites will not function at all without the use of cookies (or other similar technologies, such as "web beacons" or "tags").

  %p Cookies generally do not hold any information to identify an individual person, but are instead used to identify a browser on an individual machine.

  %p If you prefer, you can restrict, block or delete cookies by changing your browser settings but that may mean that the website won't work properly

  %p For more information about cookies and their impact on you and your browsing click the button below 
  
  .text-center
    %a{href: 'http://www.aboutcookies.org', class: 'orange-gradient-btn', target: '_blank'} About cookies

app/views/static_pages/index.html.haml
- if logged_in?
  = render 'shared/nav_logged'
  .container.main-page
    .row
      = render 'shared/flash_message'
      .user-feed.text-center
        = render 'tasks/task_form'
        .users-todo
          #todo-tasks
            %h4
              Todo (
              %span#todo_count= @todo_count
              )
            = link_to "Delete all", delete_all_task_path(@user, done: false),
                                    method: :delete, id: 'delete-all', 
                                    data: { confirm: "Are you sure you want to delete all Todo tasks?" }
            %ul.tasks
              = render @todo_tasks
          #no-tasks.text-center
            %h3.no-todo-tasks You have nothing to do :)
        .users-done
          #done-tasks
            %h4
              Done (
              %span#done_count= @done_count
              )
            = link_to "Delete all", delete_all_task_path(@user, done: true),
                                    method: :delete, id: 'delete-all', 
                                    data: { confirm: "Are you sure you want to delete all Done tasks?" }
            %ul.tasks
              = render @done_tasks
- else
  = render 'shared/nav_non_logged_in'
  .container.full-width
    .row
      = render 'shared/flash_message'
      .text-center
        = link_to 'Send activation email again', activations_path, method: :post,
                  class: 'btn orange-gradient-btn', id: "activation-btn"
        %h2.fancy-font Organize your time with ToDo list and free your mind!
      .form-white-box
        = render 'sessions/new'
  .container
    = render 'layouts/footer'

  / Modal
  = render 'shared/signup_modal'