config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#index'

  # Login 
  get     '/login',  to: 'sessions#new'
  post    '/login',  to: 'sessions#create'
  delete  '/logout', to: 'sessions#destroy'
  
  # Signup
  get     '/signup', to: 'users#new'
  post    '/signup', to: 'users#create'
  
  # OmniAuth
  get     '/auth/:provider/callback', to: 'sessions#create_omniauth'
  
  resources :users
  resources :activations,     only: [:new, :create, :edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :tasks,           only: [:create, :destroy, :edit, :update]
  resources :tasks,           only: [:change, :delete_all] do
    member do
      get :change
      delete :delete_all
    end
  end

  get     '/cookies', to: 'static_pages#cookies_eu'
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
  before_action :get_user,         only: [:edit, :update]
  before_action :valid_user,       only: [:edit, :update]
  before_action :check_expiration, only: [:edit, :update]

  def new
    @user = User.new
  end

  def create
    @user = User.find_by_email(params[:password_reset][:email].downcase)
    if @user
      if @user.provider?
        @user.send_account_info_email
      else
        @user.create_password_reset_token
        @user.send_password_reset_email
      end
      flash[:info] = "Email was sent with instructions."
      redirect_to root_url
    else
      flash[:danger] = "Email not found."
      redirect_to new_password_reset_url
    end
  end
  
  def edit
  end
  
  def update
    if params[:user][:password].empty?
      @user.errors.add(:password, "can't be empty")
      render 'edit'
    elsif @user.update_attributes(user_params)
      log_in @user
      flash[:success] = "Password has been reset."
      redirect_to root_url
    else
      render 'edit'
    end
  end

  private

    def user_params
      params.require(:user).permit(:password, :password_confirmation)
    end

    def get_user
      @user = User.find_by_email(params[:email])
    end

    def valid_user
      unless @user && @user.activated? && (@user.password_reset_token == params[:id])
        msg = "Your account was not activated."
        msg += " Check your email for activation link."
        flash[:danger] = msg
        redirect_to root_url
      end
    end

    def check_expiration
      if @user.password_reset_token_expired?
        flash[:danger] = "Password reset has expired."
        redirect_to new_password_reset_url
      end
    end
end

app/views/password_resets/edit.html.haml
= render 'shared/nav_non_logged_in'
.container.full-width
  .row
    .form-white-box.increase-margin
      .form-inside
        .inside-lines
          %h4 Set new password
        = simple_form_for(@user, url: password_reset_path(params[:id])) do |f|
          = f.input :password, placeholder: "Password", label: false
          = f.input :password_confirmation, placeholder: "Password confirmation",
                                            label: false
          = hidden_field_tag :email, @user.email
          .text-center
            = f.button :submit, "Change password", class: "btn orange-gradient-btn"

app/views/password_resets/new.html.haml
= render 'shared/nav_non_logged_in'

.container.full-width
  .row
    = render 'shared/flash_message'
    .form-white-box.increase-margin
      .form-inside
        .inside-lines
          %h4 Write your email
        = simple_form_for(:password_reset, url: password_resets_path) do |f|
          = f.input :email, placeholder: 'user@domain.com', label: false
          .text-center
            = f.button :submit, "OK!", class: "btn orange-gradient-btn"

/ Modal
= render 'shared/signup_modal'